spring.application.name=Url-Shortner

spring.datasource.url=jdbc:postgresql://localhost:5432/UrlShortener
spring.datasource.username=postgres
spring.datasource.password=Neel_1909

spring.jpa.hibernate.ddl-auto=update
